### ISSUE TITLE
require 'save-cwd doesn't work

### ISSUE THREAD

**Issue by pesterhazy** [hardaker/elisp-save-cwd#1]
I like the idea behind save-cwd.

However, if I require the file, I get the following error:

```
(error "Required feature ‘save-cwd’ was not provided")
```

**Comment by pesterhazy** [comment]
I think you'll need to add

```
(provide 'save-cwd)
```

**Comment by swflint** [comment]
I have this (and issue #2) fixed in a pull-request.  Hopefully he'll get around to accepting it some time.

**Comment by hardaker** [comment]
Yep.  I had actually fixed that locally but hadn't pushed it yet.  It's there now.
