### ISSUE TITLE
Save CWD isn't available in Melpa

### ISSUE THREAD

**Issue by swflint** [hardaker/elisp-save-cwd#6]
I've staged a recipe for melpa as HEAD on swflint/melpa.  If you approve, I can submit a pull request.

**Comment by hardaker** [comment]
I actually just wrote one in the last 2 hours too and just submitted a pull request for it.  There were issues that needed to be fixed in the package before I could create the melpa request (which have now been done).

**Comment by swflint** [comment]
Awesome!

**Comment by hardaker** [comment]
Arg.  They defined it as a bad idea:  

https://github.com/melpa/melpa/pull/4825

**Comment by swflint** [comment]
I saw.  And while I can see why they did that, I don't think it's appropriate for them to a) reject because they don't like the implementation or b) reject because it's "low quality".
